spring:
  datasource:
    url: "jdbc:h2:file:./build/prod/h2"
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    hibernate:
      ddl-auto: update
application:
  storageDir: "./build/prod/storage"
  batchSize: 1000
