spring:
  datasource:
    url: "jdbc:h2:file:./build/test/h2"
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    hibernate:
      ddl-auto: create
application:
  storageDir: "./storage"
  batchSize: 1000
