spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/fileman
    username: fileman
    password: fileman
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
      #flyway will look for files in ./db/migration
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          order_inserts: true
application:
  storagePath: "./storage"
  batchSize: 1000

logging:
  level:
    ROOT: DEBUG
    fr.dalae: DEBUG
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: debug
